################################### Default Configuration ############################
baseurl = "https://displace.tech/"
title = "Displace Technologies"
theme = "displace.tech"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = ['fr'] # disable language from here

# unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.27/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Contact"
url = "contact"
weight = 2

# footer menu

########################### Default parameters ##########################
[params]
logo_width = "100px"
# Meta data
description = "Disrupting the Status Quo"
author = "Eric Mann"
# currency
currency = "$"
# contact form action
contact_form_action = "https://formspree.io/f/mwkwydjo" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://tech.us7.list-manage.com/subscribe/post?u=4f9776a24d2f95a3b0d7d1f98&amp;id=49b5728123" # replace this url with yours
mailchimp_form_name = "b_4f9776a24d2f95a3b0d7d1f98_49b5728123" # replace this code with yours


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2021 · Design By [Themefisher](https://themefisher.com/) & [Gethugothemes](https://gethugothemes.com/)"
